apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dl1fjwm04-nodejs
  janus-idp.io/tekton: dl1fjwm04-nodejs
  backstage.io/kubernetes-id: dl1fjwm04-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dl1fjwm04-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
