apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dl1fjwm04-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dl1fjwm04-nodejs 
  name: dl1fjwm04-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dl1fjwm04-nodejs 
